query ProductsBySubcategory($subcategoryName: String!) {
	subcategories(filters: { name: { eqi: $subcategoryName } }) {
		data {
			attributes {
				name

				categoria {
					data {
						attributes {
							name
							image {
								data {
									attributes {
										url
										formats
									}
								}
							}
						}
					}
				}

				productos {
					data {
						id
						attributes {
							name
							slug
							brand
							image {
								data {
									attributes {
										name
										url
										formats
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
