query ProductsBySubcategory($subcategoryName: String!) {
	subcategories(filters: { name: { eqi: $subcategoryName } }) {
		name
		categoria {
			name
			image {
				url
				formats
			}
		}
		productos {
			documentId
			name
			slug
			link
			brand
			image {
				name
				url
				formats
			}
		}
	}
}
