query Subcategories($name: String!) {
	subcategories(filters: { categoria: { name: { eqi: $name } } }) {
		name
		image {
			name
			url
			formats
		}
		categoria {
			name
			description
			image {
				name
				url
				formats
			}
		}
		productos {
			slug
		}
	}
}
